[package]
name = "localcell"
version = "1.0.0"
edition = "2024"
license = "MIT"
authors = ["zk2u <zk2u@pm.me>"]
repository = "https://github.com/zk2u/localcell"

[dependencies]

[dev-dependencies]
futures = "0.3.31"
monoio = "0.2.4"
