[package]
name = "localcell"
description = "Compile-time checked mutable shared memory container for single-threaded async runtimes"
version = "1.1.0"
edition = "2024"
license = "MIT"
authors = ["zk2u <zk2u@pm.me>"]
repository = "https://github.com/zk2u/localcell"

[dependencies]

[dev-dependencies]
futures = "0.3.31"
monoio = "0.2.4"
criterion = { version = "0.5", features = ["html_reports"] }
tokio = { version = "1.0", features = ["sync", "rt"] }

[[bench]]
name = "localcell"
harness = false
path = "benches/localcell.rs"

[[bench]]
name = "smolqueue"
harness = false
path = "benches/smolqueue.rs"

[[bench]]
name = "mutex"
harness = false
path = "benches/mutex.rs"
